version: '3'
services:
    postgres:
        image: postgres:alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_MULTIPLE_DATABASES: ${project-name}
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
    redis:
        image: redis:alpine
        ports:
            - '7000:6379'
