version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_MULTIPLE_DATABASES: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        restart: unless-stopped
        networks:
            - sdnet
        volumes:
            - ./create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
            - db-data:/var/lib/postgresql/data
    # app:
    #     build: .
    #     ports:
    #         - '4000:4000'
    #     environment:
    #         REDIS_HOST: redis
    #         PORT: 4000
    #         NODE_ENV: development
    #         # DB_HOST: db
    #         # DB_USER: postgres
    #         # DB_PASSWORD: postgres
    #     links:
    #         - redis:localhost
    #         - db
    #     networks:
    #         - sdnet
    #     depends_on:
    #         - db
    # redis:
    #     image: redis:alpine
    #     networks:
    #         - sdnet

networks:
    sdnet:
        driver: 'bridge'
volumes:
    db-data:
