apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
    name: ${project-name}-environment
spec:
    backendType: secretsManager
    region: us-east-1
    dataFrom:
        - prod/${project-name}
